"""
Django settings for zoom_project project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
from decouple import config  # Para leer variables del .env

# ========================================
# BASE
# ========================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ========================================
# SECURITY
# ========================================

SECRET_KEY = 'django-insecure-p*i^=4v++5obyy%(c8^fjflr=!o)dagm5_5$e(917_fd!v235y'

DEBUG = True

ALLOWED_HOSTS = []

# ========================================
# ZOOM OAUTH (USER-LEVEL)
# ========================================

ZOOM_CLIENT_ID = config('ZOOM_CLIENT_ID')
ZOOM_CLIENT_SECRET = config('ZOOM_CLIENT_SECRET')

ZOOM_OAUTH_AUTHORIZE_URL = config('ZOOM_OAUTH_AUTHORIZE_URL')
ZOOM_OAUTH_TOKEN_URL = config('ZOOM_OAUTH_TOKEN_URL')
ZOOM_API_BASE_URL = config('ZOOM_API_BASE_URL')

ZOOM_REDIRECT_URI = config('ZOOM_REDIRECT_URI')

# ========================================
# APPLICATIONS
# ========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'reuniones',
]

# ========================================
# MIDDLEWARE
# ========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # sesiones
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # login
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ========================================
# URLS / TEMPLATES
# ========================================

ROOT_URLCONF = 'zoom_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # templates dentro de apps
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zoom_project.wsgi.application'

# ========================================
# DATABASE
# ========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ========================================
# PASSWORD VALIDATION
# ========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ========================================
# INTERNATIONALIZATION
# ========================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True

# ========================================
# STATIC FILES
# ========================================

STATIC_URL = 'static/'

# ========================================
# AUTH / LOGIN CONFIG (🔥 CLAVE 🔥)
# ========================================

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ========================================
# DEFAULT PK
# ========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
